### ISSUE TITLE
Backgrounds don't expand to cover viewport on large screens.

### ISSUE THREAD

**Issue by iandoesallthethings** [avinayak/minim#29]
Hello! I've been using this extension for what feels like forever, and I love it! In other good news, I just upgraded to a 4K monitor aaaaaaaand...

![minim margins](https://user-images.githubusercontent.com/15148313/172000923-429d8a9d-e4ff-4651-a225-ce6a37e3b0f7.jpg)

I think just adding `background-size: cover;` to `.background-layer` should do the trick.

![Screen Shot 2022-06-04 at 9 25 09 AM](https://user-images.githubusercontent.com/15148313/172001168-caecacef-7615-4e87-a9d8-3a411a2a41fe.jpg)
`

**Comment by avinayak** [comment]
Thanks for reporting! will fix this ASAP!

**Comment by avinayak** [comment]
Can you test something though? can you try `localStorage.clear()` in the console?

**Comment by avinayak** [comment]
Should be fixed!
