### ISSUE TITLE
Image Background not shuffling

### ISSUE THREAD

**Issue by SpazMahTazz** [avinayak/minim#36]
Firstly I love minim, it's so cool. I have it on everything that lets me set my own home page. But lately I've noticed the wallpaper hasn't been shuffling on any of my devices (see gif below).

![Capture 2022-11-30-10-05-30](https://user-images.githubusercontent.com/39617497/204667952-8bd24399-f017-4611-80c7-bd87a52b0d84.gif)

It sort of makes mimim useless for me, since I primarily use it to get new wallpapers. Changing background collection doesn't fix it.

Cheers.

**Comment by avinayak** [comment]
Hello! Thanks for reporting this. Unfortunately this is an issue with our images provider unsplash.com. I'm actively monitoring the issue. 
Apologies! I'll ping here when they fix the issue.

**Comment by avinayak** [comment]
@SpazMahTazz This issue should be resolved now.
